class StrRef{
  static String onBoardTitle1 = "Welcome to Festopost",
  onBoardTitle2 = "Simplified Post Creation",
  onBoardTitle3 = "Download and Share",
  onBoardDesc1 = "Celebrate Festivals and Boost Your Business with Our Posts and Offers.",
  onBoardDesc2 = "Connect with your customers on every holiday with creative posts.",
  onBoardDesc3 = "Easy to Download and Share Posts on Social Media",
  getStart = "Get Started",
  skip = "Skip",
  registerTitle1 = "Welcome to ",
  registerTitle2 = "Festo Post",
  register = "Register",
  login = "Login",
  contact = "Mobile Number",
  verify = "Verify By WhatsApp",
  whatsApp = "I Don't Have WhatsApp",
  sms = "Verify By SMS.",
  accountExists = "Already have an account?",
  accountNotExists = "Don't have an account?",
  otp = "Verify OTP",
  otpTitle = "Please Enter OTP Send To Your Registered Mobile Number",
  resendOtp = "Didn't receive OTP?",
  verifyText = "Verify",
  verified = "Verified",
  success = "Successfully!!!",
  referral = "Referral Code",
  referralTittle = "Enter Referral Code And Earn Your",
  reward = "Reward."
  ;}

  class SvgPath{
    static String onBoardImg1 = 'assets/svg/onboard1.svg' ,
    onBoardImg2 = 'assets/svg/onboard2.svg' ,
    onBoardImg3 = 'assets/svg/onboard3.svg' ,
    registerImg1 = 'assets/svg/register.svg',
    loginImg1 = 'assets/svg/loginImg.svg',
    otpImg = 'assets/svg/otp.svg',
    otpSuccess = 'assets/svg/otpsuccess.svg',
    referral = 'assets/svg/referral.svg'
  ;}
